version: '3.9'

services:
  redis_db:
    image: 'redis:alpine'
    container_name: '{containers_prefix}redis_db'
    command: redis-server
    volumes:
      - ./data/redis-data:/data

  db-init:
    image: postgres:15
    container_name: '{containers_prefix}db-init'
    volumes:
      - ./data/blockscout-db-data:/var/lib/postgresql/data
    entrypoint:
      - sh
      - -c
      - |
        chown -R 2000:2000 /var/lib/postgresql/data

  db:
    depends_on:
      db-init:
        condition: service_completed_successfully
    image: postgres:15
    user: 2000:2000
    shm_size: 256m
    restart: always
    container_name: '{containers_prefix}db'
    command: postgres -c 'max_connections=500' -c 'client_connection_check_interval=60000'
    environment:
        POSTGRES_DB: 'blockscout'
        POSTGRES_USER: 'blockscout'
        POSTGRES_PASSWORD: 'ceWb1MeLBEeOIfk65gU8EjF8'
    ports:
      - "{postgres_port}:5432"
    volumes:
      - ./data/blockscout-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockscout -d blockscout"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  backend:
    image: nearaurora/blockscout:latest
    container_name: '{containers_prefix}backend'
    build:
      context: blockscout/.
      dockerfile:  ../config/Dockerfile.backend
    deploy:
      resources:
        limits:
          cpus: "{cpu_limit}"
    pull_policy: if_not_present
    restart: always
    stop_grace_period: 5m
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  config/common-blockscout.env
    volumes:
      - ./data/logs/:/app/logs/
    depends_on:
      - db
      - redis_db
    links:
      - db:database
    command: "mix do ecto.create, ecto.migrate, phx.server"
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: "{rpc_http_protocol}://{rpc_url}"
      JSON_RPC: "{rpc_http_protocol}://{rpc_url}"
      ETHEREUM_JSONRPC_WS_URL: "{rpc_ws_protocol}://{rpc_url}"
      ETHEREUM_JSONRPC_TRACE_URL: "{rpc_http_protocol}://{rpc_url}"
      SUPPORTED_CHAINS: '[{ "title": "Mainnet", "url": "https://{explorer_url}" }]'
      BLOCKSCOUT_HOST: "{explorer_url}"
      CHAIN_ID: {chain_id}
      SECRET_KEY_BASE: {secret_key_base}
      FIRST_BLOCK: "{genesis}"
      TRACE_FIRST_BLOCK: "{genesis}"
      MICROSERVICE_SC_VERIFIER_URL: "{verifier_url}"
      MICROSERVICE_SC_VERIFIER_TYPE: "{verifier_type}"
  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    container_name: '{containers_prefix}visualizer'
    pull_policy: always
    platform: linux/amd64
    restart: always
    env_file:
      -  config/common-visualizer.env

  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-latest}
    container_name: '{containers_prefix}sig-provider'
    pull_policy: always
    platform: linux/amd64
    restart: always

  frontend:
    image: nearaurora/blockscout-frontend:latest
    container_name: '{containers_prefix}frontend'
    build:
      context: blockscout-frontend/.
      dockerfile:  Dockerfile
    pull_policy: if_not_present
    platform: linux/amd64
    restart: always
    env_file:
      -  config/common-frontend.env
    depends_on:
      - 'backend'
    environment:
      NEXT_PUBLIC_IS_TESTNET: "{is_testnet}"
      NEXT_PUBLIC_API_HOST: {explorer_url}
      NEXT_PUBLIC_STATS_API_HOST: "{blockscout_http_protocol}://{stats_api_host}"
      NEXT_PUBLIC_NETWORK_NAME: {name}
      NEXT_PUBLIC_NETWORK_SHORT_NAME: {name}
      NEXT_PUBLIC_NETWORK_ID: {chain_id}
      NEXT_PUBLIC_APP_HOST: {explorer_url}
      NEXT_PUBLIC_VISUALIZE_API_HOST: "{blockscout_http_protocol}://{visualizer_api_host}"
      NEXT_PUBLIC_AD_BANNER_PROVIDER: none
      NEXT_PUBLIC_AD_TEXT_PROVIDER: none
      NEXT_PUBLIC_NETWORK_VERIFICATION_TYPE: validation
      NEXT_PUBLIC_NEAR_NETWORK: {network}
      NEXT_PUBLIC_NETWORK_RPC_URL: "{rpc_http_protocol}://{rpc_url}"
      FAVICON_GENERATOR_API_KEY: {favicon_generator_api_key}
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: {wallet_connect_project_id}
      NEXT_PUBLIC_API_PROTOCOL: {blockscout_http_protocol}
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: {blockscout_ws_protocol}
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: {currency_symbol}
      NEXT_PUBLIC_NETWORK_LOGO: {network_logo}
      NEXT_PUBLIC_NETWORK_LOGO_DARK: {network_logo_dark}
      NEXT_PUBLIC_NETWORK_ICON: {network_icon}
      # NEXT_PUBLIC_API_PORT: 443
      # NEXT_PUBLIC_HOMEPAGE_CHARTS: '[]'
      # NEXT_PUBLIC_FEATURED_NETWORKS: https://raw.githubusercontent.com/aurora-is-near/blockscout-frontend/main/public/static/featured_networks/aurora.json

  stats:
    image: ghcr.io/blockscout/stats:${STATS_DOCKER_TAG:-latest}
    container_name: '{containers_prefix}stats'
    pull_policy: always
    platform: linux/amd64
    restart: always
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  config/common-stats.env
    environment:
      - STATS__DB_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/stats
      - STATS__BLOCKSCOUT_DB_URL=postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true

  smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-latest}
    container_name: '{containers_prefix}smart-contract-verifier'
    pull_policy: always
    platform: linux/amd64
    restart: {smart_contract_verifier_restart_policy}
    env_file:
      - config/common-smart-contract-verifier.env
    {smart_contract_verifier_disabled}

  proxy:
    image: nginx
    container_name: '{containers_prefix}proxy'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "./data/proxy:/etc/nginx/templates"
    restart: always
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - "{blockscout_port}:80"
      - "{stats_service_port}:8080"
      - "{visualizer_service_port}:8081"
      {smart_contract_verifier_port_mapping}
    depends_on:
      - backend
      - frontend
      - stats